# Tareas para pushear las imagenes en el ACR

- name: Actualizar repositorios APT e instalar Podman y dependencias
  become: true
  import_role:
    name: common
    tasks_from: install_podman.yml

- name: Inicia sesion en el ACR con las credenciales de terraform
  import_role:
    name: common
    tasks_from: acr_login.yml

- name: Procesar y pushear imagenes al ACR
  include_tasks: push_images.yml
  loop: "{{ images_acr_2 }}"
  loop_control:
    loop_var: item