# Tareas para pushear las imagenes en el ACR

- name: Actualizar repositorios APT e instalar Podman y dependencias
  become: true
  import_role:
    name: common
    tasks_from: install_podman.yml

- name: Inicia sesion en el ACR con las credenciales de terraform
  import_role:
    name: common
    tasks_from: acr_login.yml

- name: Procesar y pushear imagen postgres al ACR
  include_tasks: push_images.yml
  loop: "{{ image_postgres }}"
  loop_control:
    loop_var: item

- name: Procesar y pushear imagen de Nginx al ACR
  include_tasks: push_images.yml
  loop: "{{ image_nginx }}"
  loop_control:
    loop_var: item

- name: Procesar y pushear imagen del Backend al ACR
  include_tasks: push_images.yml
  loop: "{{ image_backend }}"
  loop_control:
    loop_var: item