# Tarea para preparar las imagenes para el ACR
- name: Build de la imagen
  containers.podman.podman_image:
    name: "{{ item.name }}"
    path: "{{ item.source }}"
    build:
      format: docker
    force: true

- name: Tag de la imagen
  containers.podman.podman_tag:
    image: "{{ item.name }}:{{ item.tag }}"
    target_names:
      - "{{ acr_login_server }}/{{ item.name }}:{{ item.tag }}"

- name: Push de la imagen al ACR
  containers.podman.podman_image:
    name: "{{ acr_login_server }}/{{ item.name }}"
    tag: "{{ item.tag }}"
    push: true