# Tarea para preparar las imagenes para el ACR
- name: Build de la imagen
  containers.podman.podman_image:
    name: "{{ imagen_acr_1_name }}"
    path: "{{ imagen_acr_1_path }}"
    build:
      format: docker
    force: true

- name: Tag de la imagen
  containers.podman.podman_tag:
    image: "{{ imagen_acr_1_name }}:{{ imagen_acr_1_tag }}"
    target_names:
      - "{{ acr_login_server }}/{{ imagen_acr_1_name }}:{{ imagen_acr_1_tag }}"

- name: Push de la imagen al ACR
  containers.podman.podman_image:
    name: "{{ acr_login_server }}/{{ imagen_acr_1_name }}"
    tag: "{{ imagen_acr_1_tag }}"
    push: true