# Cierra sesión previa en ACR (si existe) para evitar conflictos
- name: Cerrar sesión previa en ACR (si existe)
  command: podman logout "{{ acr_login_server }}"
  register: logout_result
  failed_when: false
  changed_when: "'not logged into' not in logout_result.stderr"

# Inicia sesión en el ACR con las credenciales de terraform
- name: Iniciar sesion en el ACR
  containers.podman.podman_login:
    registry: "{{ acr_login_server }}"
    username: "{{ acr_admin_username }}"
    password: "{{ acr_admin_password }}"