# ---------- RUNTIME ----------
FROM docker.io/josegcort/crud-categories:latest
 
# Variables de entorno por defecto (se sobreescriben en AKS con Secrets)
ENV HOST_DB_MAIN=localhost
ENV PORT_DB_MAIN=5432
ENV NAME_DB_MAIN=userdb
ENV USER=user
ENV PASSWORD=******
 
# Puerto expuesto por la aplicación
EXPOSE 8060

# Comando de inicio (heredado de la imagen base)
CMD []
 