# Tarea para configurar la VM con Ansible y Nginx utilizando Podman

- name: Actualizar repositorios APT e instalar Podman y dependencias
  import_role:
    name: common
    tasks_from: install_podman.yml

- name: Inicia sesion en el ACR con las credenciales de terraform
  import_role:
    name: common
    tasks_from: acr_login.yml

- name: Descarga y ejecuta la imagen de nginx desde el ACR
  include_tasks: deploy_container.yml
  loop: "{{ image_nginx }}"
  loop_control:
    loop_var: item
