# Contenedor no requiere persistencia
images_acr_2:
  - name: nginxcp2
    path: "./roles/acr/dockerfiles/nginxcp2"
    deploy: "nginxcp2-deployment"
    tag: "latest"
    service: "nginxcp2-service"

aks_namespace: "aks-ns"
aks_secret: "acr-secret"

aks_pvc: "aks-pvc"
aks_app: "aks-app"

dockerconfigjson: |
  {
    "auths": {
      "{{ acr_login_server }}": {
        "username": "{{ acr_admin_username }}",
        "password": "{{ acr_admin_password }}",
        "auth": "{{ (acr_admin_username + ':' + acr_admin_password) | b64encode }}"
      }
    }
  }