# Contenedor requiere persistencia
images_acr_1:
  - name: postgrescp2
    path: "./roles/acr/dockerfiles/postgrescp2"
    deploy: "postgrescp2-deployment"
    tag: "latest"
    service: "postgrescp2-service"
    app: "postgrescp2-app"
    pvc: "postgrescp2-pvc"
    mount_path: "/var/lib/postgresql/data"
    storage: "postgrescp2-storage"
    storage_size: 2Gi
    port_in: 5432
    port_out: 5432

# Contenedor no requiere persistencia
images_acr_2:
  - name: nginxcp2
    path: "./roles/acr/dockerfiles/nginxcp2"
    deploy: "nginxcp2-deployment"
    tag: "latest"
    service: "nginxcp2-service"
    app: "nginxcp2-app"
    port_in: 80
    port_out: 80

# Contenedor no requiere persistencia
images_acr_3:
  - name: nginxcp2
    path: "./roles/acr/dockerfiles/nginxcp2"
    deploy: "nginxcp2-deployment"
    tag: "latest"
    service: "nginxcp2-service"
    app: "nginxcp2-app"
    port_in: 80
    port_out: 80

# Variables para AKS
aks_namespace: "aks-ns"
aks_secret: "acr-secret"

# Autenticación para ACR en formato json
dockerconfigjson: |
  {
    "auths": {
      "{{ acr_login_server }}": {
        "username": "{{ acr_admin_username }}",
        "password": "{{ acr_admin_password }}",
        "auth": "{{ (acr_admin_username + ':' + acr_admin_password) | b64encode }}"
      }
    }
  }