# Tarea para crear el deployment de postgres en AKS
- name: Crear deployment
  kubernetes.core.k8s:
    kubeconfig: "{{ aks_kubeconfig_path }}"
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ item.deploy }}"
        namespace: "{{ aks_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ item.app }}"
        template:
          metadata:
            labels:
              app: "{{ item.app }}"
          spec:
            imagePullSecrets:
              - name: "{{ aks_secret }}"
            containers:
              - name: "{{ item.app }}"
                image: "{{ acr_login_server }}/{{ item.name }}:{{ item.tag }}"
                envFrom:
                  - secretRef:
                      name: "{{ item.secret }}"
                ports:
                  - containerPort: "{{ item.port_in }}"
                env:
                  - name: "{{ item.env_name }}"
                    value: "{{ item.env_value }}"
                volumeMounts:
                  - mountPath: "{{ item.mount_path }}"
                    name: "{{ item.storage }}"
            volumes:
              - name: "{{ item.storage }}"
                persistentVolumeClaim:
                  claimName: "{{ item.pvc }}"