# Tareas para el despliegue de imagenes en el AKS

- name: Actualizar repositorios APT e instalar librerías de python
  become: true
  import_tasks: install_pip.yml

- name: Crear namespace en AKS
  import_tasks: namespace.yml

- name: Crear secreto ACR en AKS para hacer pull de imagenes privadas
  import_tasks: secret_acr.yml

- name: Contenedorizar y desplegar postgres
  import_tasks: deploy_postgres.yml

- name: Contenedorizar y desplegar backend
  import_tasks: deploy_backend.yml