# Tareas para el despliegue de imagenes en el AKS

- name: Actualizar repositorios APT e instalar librerías de python
  become: true
  import_tasks: install_pip.yml

- name: Crear namespace
  import_tasks: namespace.yml

- name: Crear secreto ACR
  import_tasks: secret_acr.yml

- name: Contenedorizar aplicación aplicacion persistente 
  import_tasks: with_pvc.yml

- name: Contenedorizar aplicación aplicacion no persistente 
  import_tasks: without_pvc.yml