# Tarea para crear un secret en AKS con las credenciales de PostgreSQL
- name: Crear secret para PostgreSQL
  kubernetes.core.k8s:
    kubeconfig: "{{ aks_kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ item.secret }}"
        namespace: "{{ aks_namespace }}"
      type: Opaque
      stringData:
        POSTGRES_USER: "{{ postgres_user }}"
        POSTGRES_PASSWORD: "{{ postgres_password }}"
        POSTGRES_DB: "{{ postgres_db }}"