
- name: Crear secret para ACR
  kubernetes.core.k8s:
    kubeconfig: "{{ aks_kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ aks_secret }}"
        namespace: "{{ aks_namespace }}"
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ dockerconfigjson | b64encode }}"