# Tarea para crear un secret en AKS con las credenciales de Backend
- name: Crear secret para Backend
  kubernetes.core.k8s:
    kubeconfig: "{{ aks_kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ item.secret }}"
        namespace: "{{ aks_namespace }}"
      type: Opaque
      stringData:
        HOST_DB_MAIN: "{{ image_postgres[0].service }}"
        PORT_DB_MAIN: "{{ image_postgres[0].port_out | string }}"
        NAME_DB_MAIN: "{{ postgres_db }}"
        USER: "{{ postgres_user }}"
        PASSWORD: "{{ postgres_password }}"