
- name: Crear servicio LoadBalancer
  kubernetes.core.k8s:
    kubeconfig: "{{ aks_kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ aks_service }}"
        namespace: "{{ aks_namespace }}"
      spec:
        type: LoadBalancer
        selector:
          app: "{{ aks_app }}"
        ports:
          - port: 80
            targetPort: 80