# Desplegar y exponer contenedor sin PVC
- name: Desplegar aplicación
  include_tasks: deployment.yml
  loop: "{{ images_acr_2 }}"
  loop_control:
    loop_var: item

- name: Exponer externamente aplicación
  include_tasks: service_out.yml
  loop: "{{ images_acr_2 }}"
  loop_control:
    loop_var: item