# Tarea para preparar las imagenes en el ACR
- name: Build y push de imagenes al ACR
  hosts: localhost
  gather_facts: false
  roles:
    - acr

# Tarea para configurar la VM para desplegar contenedor utilizando Podman
- hosts: vm
  become: true
  roles:
    - vm

# Tarea para configurar el AKS y desplegar contenedores
- name: Configurar AKS
  hosts: localhost
  gather_facts: false
  roles:
    - aks