# Tarea para preparar las imagenes en el ACR
- name: Hace build y push de imagenes al ACR
  hosts: localhost
  gather_facts: false
  roles:
    - acr

# Tarea para configurar la VM para desplegar contenedor utilizando Podman
- name: Configurar VM
  hosts: vm
  become: true
  roles:
    - vm

# Tarea para configurar el AKS y desplegar contenedores
- name: Configurar AKS
  hosts: localhost
  gather_facts: false
  roles:
    - aks

# Tarea para obtener y mostrar las direcciones IPs publicas de los servicios desplegados en AKS y VM
- name: Muestrar direcciones IPs publicas de los servicios desplegados
  hosts: localhost
  gather_facts: false
  roles:
    - msg